### ISSUE TITLE
TypeError: can't pickle _thread.lock objects

### ISSUE THREAD

**Issue by fera0013** [yuanqing811/ISIC2018#9]
Running cls_train.py with debug_visualize = True triggered the following error:

```
Epoch 1/50
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\data_utils.py", line 548, in _run
    with closing(self.executor_fn(_SHARED_SEQUENCES)) as executor:
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\data_utils.py", line 522, in <lambda>
    initargs=(seqs,))
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py", line 174, in __init__
    self._repopulate_pool()
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py", line 239, in _repopulate_pool
    w.start()
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle _thread.lock objects

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
```

There may be a problem with

```
def save_model_config(run_name, **model_config):
    config_file = get_model_config_filename(run_name=run_name)
    with open(config_file, 'wb') as file:
        pickle.dump(model_config, file)
```
Apparently, [using pickle to save Keras models is not recommended](https://keras.io/getting-started/faq/#how-can-i-save-a-keras-model).

**Comment by yuanqing811** [comment]
Thank you for reporting the issue. I was not successful in replicating your error, Pickler was used to save model training parameters (stored in a Python dictionary), and is non-essential. I have removed them and hope that resolves the issue. The actual Keras model is saved to json (architecture) and hdf5 files (weights). I would suggest setting the debug flag to False when you are actually training your model.

**Comment by fera0013** [comment]
Absolutelely, but before I start training on the complete dataset, I need to make sure that the code completes correctly on the reduced debug dataset.
